name: 'Robot 2'
spin_rate: 1.0           # in Hertz
broadcast_rate: 0.6      # in Hertz
timeout_duration: 2.5    # in seconds
buffer_horizon: 10.0     # in seconds
sensors:
  size: 2
  sensor0:
    plugin_name: 'alliance_test/odometry'
    topic_name: 'odom'
    timeout_duration: 6.0
    buffer_horizon: 5.5
  sensor1:
    plugin_name: 'alliance_test/point_cloud'
    topic_name: 'sonar'
    timeout_duration: 4.0
    buffer_horizon: 6.0
behaviour_sets:
  size: 3
  behaviour_set0:
    task_id: 'wander'
    task_expected_duration: 150.0 # in seconds
    motivational_behaviour:
      threshold: 100.0
      acquiescence:
        yielding_delay: 180.0   # in seconds
        giving_up_delay: 200.0  # in seconds
      impatience:
        fast_rate: 10.0
      sensory_feedback:
        plugin_name: 'alliance_test/updated_sensory'
        sensors:
          size: 1
          sensor0:
            topic_name: 'sonar'
  behaviour_set1:
    task_id: 'border_protection'
    task_expected_duration: 250.0 # in seconds
    motivational_behaviour:
      threshold: 300.0
      acquiescence:
        yielding_delay: 200.0   # in seconds
        giving_up_delay: 350.0  # in seconds
      impatience:
        fast_rate: 5.0
      sensory_feedback:
        plugin_name: 'alliance_test/updated_sensory'
        sensors:
          size: 2
          sensor0:
            topic_name: 'sonar'
          sensor1:
            topic_name: 'odom'
  behaviour_set2:
    task_id: 'report'
    task_expected_duration: 250.0 # in seconds
    motivational_behaviour:
      threshold: 250.0
      acquiescence:
        yielding_delay: 20.0   # in seconds
        giving_up_delay: 50.0  # in seconds
      impatience:
        fast_rate: 15.0
      sensory_feedback:
        plugin_name: 'alliance_test/updated_sensory'
        sensors:
          size: 2
          sensor0:
            topic_name: 'odom'
          sensor1:
            topic_name: 'sonar'
